export const abisV4 = [
  {
    name: 'AllowedAdapterIncomingAssetsPolicy',
    version: '4',
    file: './abis/v4/AllowedAdapterIncomingAssetsPolicy.json',
  },
  { name: 'AllowedDepositRecipientsPolicy', version: '4', file: './abis/v4/AllowedDepositRecipientsPolicy.json' },
  { name: 'CompoundDebtPositionLib', version: '4', file: './abis/v4/CompoundDebtPositionLib.json' },
  { name: 'ComptrollerLib', version: '4', file: './abis/v4/ComptrollerLib.json' },
  { name: 'EntranceRateBurnFee', version: '4', file: './abis/v4/EntranceRateBurnFee.json' },
  { name: 'EntranceRateDirectFee', version: '4', file: './abis/v4/EntranceRateDirectFee.json' },
  { name: 'ExitRateBurnFee', version: '4', file: './abis/v4/ExitRateBurnFee.json' },
  { name: 'ExitRateDirectFee', version: '4', file: './abis/v4/ExitRateDirectFee.json' },
  { name: 'ExternalPositionFactory', version: '4', file: './abis/v4/ExternalPositionFactory.json' },
  { name: 'ExternalPositionManager', version: '4', file: './abis/v4/ExternalPositionManager.json' },
  { name: 'FeeManager', version: '4', file: './abis/v4/FeeManager.json' },
  { name: 'FundDeployer', version: '4', file: './abis/v4/FundDeployer.json' },
  { name: 'GasRelayPaymasterFactory', version: '4', file: './abis/v4/GasRelayPaymasterFactory.json' },
  { name: 'GasRelayPaymasterLib', version: '4', file: './abis/v4/GasRelayPaymasterLib.json' },
  { name: 'GlobalConfigLib', version: '4', file: './abis/v4/GlobalConfigLib.json' },
  { name: 'GuaranteedRedemptionPolicy', version: '4', file: './abis/v4/GuaranteedRedemptionPolicy.json' },
  { name: 'IntegrationManager', version: '4', file: './abis/v4/IntegrationManager.json' },
  { name: 'ManagementFee', version: '4', file: './abis/v4/ManagementFee.json' },
  { name: 'MinMaxInvestmentPolicy', version: '4', file: './abis/v4/MinMaxInvestmentPolicy.json' },
  { name: 'PerformanceFee', version: '4', file: './abis/v4/PerformanceFee.json' },
  { name: 'PolicyManager', version: '4', file: './abis/v4/PolicyManager.json' },
  { name: 'ProtocolFeeReserveLib', version: '4', file: './abis/v4/ProtocolFeeReserveLib.json' },
  { name: 'ProtocolFeeTracker', version: '4', file: './abis/v4/ProtocolFeeTracker.json' },
  { name: 'ValueInterpreter', version: '4', file: './abis/v4/ValueInterpreter.json' },
  { name: 'VaultLib', version: '4', file: './abis/v4/VaultLib.json' },
];
