export const abisV4 = [
  { name: 'AaveDebtPositionLib', version: '4', file: './abis/v4/AaveDebtPositionLib.json' },
  { name: 'AddressListRegistry', version: '4', file: './abis/v4/AddressListRegistry.json' },
  {
    name: 'AllowedAdapterIncomingAssetsPolicy',
    version: '4',
    file: './abis/v4/AllowedAdapterIncomingAssetsPolicy.json',
  },
  { name: 'AllowedAdaptersPolicy', version: '4', file: './abis/v4/AllowedAdaptersPolicy.json' },
  { name: 'AllowedAssetsForRedemptionPolicy', version: '4', file: './abis/v4/AllowedAssetsForRedemptionPolicy.json' },
  { name: 'AllowedDepositRecipientsPolicy', version: '4', file: './abis/v4/AllowedDepositRecipientsPolicy.json' },
  {
    name: 'AllowedExternalPositionTypesPerManagerPolicy',
    version: '4',
    file: './abis/v4/AllowedExternalPositionTypesPerManagerPolicy.json',
  },
  {
    name: 'AllowedExternalPositionTypesPolicy',
    version: '4',
    file: './abis/v4/AllowedExternalPositionTypesPolicy.json',
  },
  { name: 'AllowedAdaptersPerManagerPolicy', version: '4', file: './abis/v4/AllowedAdaptersPerManagerPolicy.json' },
  {
    name: 'AllowedSharesTransferRecipientsPolicy',
    version: '4',
    file: './abis/v4/AllowedSharesTransferRecipientsPolicy.json',
  },
  { name: 'CompoundDebtPositionLib', version: '4', file: './abis/v4/CompoundDebtPositionLib.json' },
  { name: 'ComptrollerLib', version: '4', file: './abis/v4/ComptrollerLib.json' },
  { name: 'CumulativeSlippageTolerancePolicy', version: '4', file: './abis/v4/CumulativeSlippageTolerancePolicy.json' },
  { name: 'EntranceRateBurnFee', version: '4', file: './abis/v4/EntranceRateBurnFee.json' },
  { name: 'EntranceRateDirectFee', version: '4', file: './abis/v4/EntranceRateDirectFee.json' },
  { name: 'ExitRateBurnFee', version: '4', file: './abis/v4/ExitRateBurnFee.json' },
  { name: 'ExitRateDirectFee', version: '4', file: './abis/v4/ExitRateDirectFee.json' },
  { name: 'ExternalPositionFactory', version: '4', file: './abis/v4/ExternalPositionFactory.json' },
  { name: 'ExternalPositionManager', version: '4', file: './abis/v4/ExternalPositionManager.json' },
  { name: 'FeeManager', version: '4', file: './abis/v4/FeeManager.json' },
  { name: 'FundDeployer', version: '4', file: './abis/v4/FundDeployer.json' },
  { name: 'GasRelayPaymasterFactory', version: '4', file: './abis/v4/GasRelayPaymasterFactory.json' },
  { name: 'GasRelayPaymasterLib', version: '4', file: './abis/v4/GasRelayPaymasterLib.json' },
  { name: 'IExternalPositionProxy', version: '4', file: './abis/v4/IExternalPositionProxy.json' },
  { name: 'IntegrationManager', version: '4', file: './abis/v4/IntegrationManager.json' },
  { name: 'ManagementFee', version: '4', file: './abis/v4/ManagementFee.json' },
  {
    name: 'MinAssetBalancesPostRedemptionPolicy',
    version: '4',
    file: './abis/v4/MinAssetBalancesPostRedemptionPolicy.json',
  },
  { name: 'MinMaxInvestmentPolicy', version: '4', file: './abis/v4/MinMaxInvestmentPolicy.json' },
  { name: 'MinSharesSupplyFee', version: '4', file: './abis/v4/MinSharesSupplyFee.json' },
  {
    name: 'NoDepegOnRedeemSharesForSpecificAssetsPolicy',
    version: '4',
    file: './abis/v4/NoDepegOnRedeemSharesForSpecificAssetsPolicy.json'
  },
  {
    name: 'OnlyRemoveDustExternalPositionPolicy',
    version: '4',
    file: './abis/v4/OnlyRemoveDustExternalPositionPolicy.json',
  },
  {
    name: 'OnlyUntrackDustOrPricelessAssetsPolicy',
    version: '4',
    file: './abis/v4/OnlyUntrackDustOrPricelessAssetsPolicy.json',
  },
  { name: 'PerformanceFee', version: '4', file: './abis/v4/PerformanceFee.json' },
  { name: 'PolicyManager', version: '4', file: './abis/v4/PolicyManager.json' },
  { name: 'ProtocolFeeReserveLib', version: '4', file: './abis/v4/ProtocolFeeReserveLib.json' },
  { name: 'ProtocolFeeTracker', version: '4', file: './abis/v4/ProtocolFeeTracker.json' },
  { name: 'UintListRegistry', version: '4', file: './abis/v4/UintListRegistry.json' },
  { name: 'UnpermissionedActionsWrapper', version: '4', file: './abis/v4/UnpermissionedActionsWrapper.json' },
  { name: 'ValueInterpreter', version: '4', file: './abis/v4/ValueInterpreter.json' },
  { name: 'VaultLib', version: '4', file: './abis/v4/VaultLib.json' },
];
