export const abisV2 = [
  { name: 'AdapterBlacklist', version: '2', file: './abis/v2/AdapterBlacklist.json' },
  { name: 'AdapterWhitelist', version: '2', file: './abis/v2/AdapterWhitelist.json' },
  { name: 'AggregatedDerivativePriceFeed', version: '2', file: './abis/v2/AggregatedDerivativePriceFeed.json' },
  { name: 'AssetBlacklist', version: '2', file: './abis/v2/AssetBlacklist.json' },
  { name: 'AssetWhitelist', version: '2', file: './abis/v2/AssetWhitelist.json' },
  { name: 'BuySharesCallerWhitelist', version: '2', file: './abis/v2/BuySharesCallerWhitelist.json' },
  { name: 'ChainlinkPriceFeed', version: '2', file: './abis/v2/ChainlinkPriceFeed.json' },
  { name: 'ComptrollerLib', version: '2', file: './abis/v2/ComptrollerLib.json' },
  { name: 'EntranceRateBurnFee', version: '2', file: './abis/v2/EntranceRateBurnFee.json' },
  { name: 'EntranceRateDirectFee', version: '2', file: './abis/v2/EntranceRateDirectFee.json' },
  { name: 'FeeManager', version: '2', file: './abis/v2/FeeManager.json' },
  { name: 'FundDeployer', version: '2', file: './abis/v2/FundDeployer.json' },
  { name: 'GuaranteedRedemption', version: '2', file: './abis/v2/GuaranteedRedemption.json' },
  { name: 'IntegrationManager', version: '2', file: './abis/v2/IntegrationManager.json' },
  { name: 'InvestorWhitelist', version: '2', file: './abis/v2/InvestorWhitelist.json' },
  { name: 'ManagementFee', version: '2', file: './abis/v2/ManagementFee.json' },
  { name: 'MaxConcentration', version: '2', file: './abis/v2/MaxConcentration.json' },
  { name: 'MinMaxInvestment', version: '2', file: './abis/v2/MinMaxInvestment.json' },
  { name: 'PerformanceFee', version: '2', file: './abis/v2/PerformanceFee.json' },
  { name: 'PolicyManager', version: '2', file: './abis/v2/PolicyManager.json' },
  { name: 'ValueInterpreter', version: '2', file: './abis/v2/ValueInterpreter.json' },
  { name: 'VaultLib', version: '2', file: './abis/v2/VaultLib.json' },
];
