export const abisV3 = [
  { name: 'AdapterBlacklist', version: '3', file: './abis/v3/AdapterBlacklist.json' },
  { name: 'AdapterWhitelist', version: '3', file: './abis/v3/AdapterWhitelist.json' },
  { name: 'AggregatedDerivativePriceFeed', version: '3', file: './abis/v3/AggregatedDerivativePriceFeed.json' },
  { name: 'AssetBlacklist', version: '3', file: './abis/v3/AssetBlacklist.json' },
  { name: 'AssetWhitelist', version: '3', file: './abis/v3/AssetWhitelist.json' },
  { name: 'BuySharesCallerWhitelist', version: '3', file: './abis/v3/BuySharesCallerWhitelist.json' },
  { name: 'ChainlinkPriceFeed', version: '3', file: './abis/v3/ChainlinkPriceFeed.json' },
  { name: 'ComptrollerLib', version: '3', file: './abis/v3/ComptrollerLib.json' },
  { name: 'EntranceRateBurnFee', version: '3', file: './abis/v3/EntranceRateBurnFee.json' },
  { name: 'EntranceRateDirectFee', version: '3', file: './abis/v3/EntranceRateDirectFee.json' },
  { name: 'FeeManager', version: '3', file: './abis/v3/FeeManager.json' },
  { name: 'FundActionsWrapper', version: '3', file: './abis/v3/FundActionsWrapper.json' },
  { name: 'FundDeployer', version: '3', file: './abis/v3/FundDeployer.json' },
  { name: 'GuaranteedRedemption', version: '3', file: './abis/v3/GuaranteedRedemption.json' },
  { name: 'IntegrationManager', version: '3', file: './abis/v3/IntegrationManager.json' },
  { name: 'InvestorWhitelist', version: '3', file: './abis/v3/InvestorWhitelist.json' },
  { name: 'ManagementFee', version: '3', file: './abis/v3/ManagementFee.json' },
  { name: 'MaxConcentration', version: '3', file: './abis/v3/MaxConcentration.json' },
  { name: 'MinMaxInvestment', version: '3', file: './abis/v3/MinMaxInvestment.json' },
  { name: 'PerformanceFee', version: '3', file: './abis/v3/PerformanceFee.json' },
  { name: 'PolicyManager', version: '3', file: './abis/v3/PolicyManager.json' },
  { name: 'ValueInterpreter', version: '3', file: './abis/v3/ValueInterpreter.json' },
  { name: 'VaultLib', version: '3', file: './abis/v3/VaultLib.json' },
];
